### ISSUE TITLE
Framework does not include symbols from NSManagedObjectContext

### ISSUE THREAD

**Issue by MobileVet** [jessesquires/JSQCoreDataKit#84] opened 2016-06-03 15:24 UTC
When attempting to call 'delete' I am receiving a -[NSManagedObjectContext delete:]: unrecognized selector sent to instance 0x79e53be0. 

Placing breakpoints in the extension, I can quickly see that the JSQCoreDataKit NSManagedObjectContext extension is NOT called, which makes it understandable why the above error as 'delete' is being called

Other included frameworks with extensions have worked ok... and I see that the example project works fine.  No idea why these symbols are being lost, though a SO post sheds some light on the issue being known for 'generics'

## General information

- Library version(s): 4.0.1
- OS version(s): iOS 9.3
- Devices/Simulators affected: iPhone 5 simulator
- Reproducible in the demo project (Yes/No): No
- Related issues: [http://stackoverflow.com/questions/24175596/swift-framework-does-not-include-symbols-from-extensions-to-generic-structs]

## Expected behavior

Object is deleted

## Actual behavior

`-[NSManagedObjectContext delete:]: unrecognized selector sent to instance 0x79e53be0`

## Steps to reproduce

1. Include framework within the project.  
2. Add framework to the appropriate Build Phases.
3. Call `self.stack?.mainContext.delete(obj)`

**Comment by jessesquires** [comment] 2016-06-03 15:49
Thanks @MobileVet ! 😄 

This method changed in 4.0 of the library, it should be:

```swift
context.delete(objects: [obj])
```

Let me know if this doesn't work!

**Comment by saurabytes** [comment] 2016-06-03 15:52
@jessesquires this new method is actually causing the error. I had to write a top level function in my framework to call this `delete` method, calling it via a context was erroring everywhere after migration

**Comment by MobileVet** [comment] 2016-06-03 17:18
Sorry I wasn't more clear, I am actually calling:
`context.delete(objects: [obj])`

As @saurabytes indicated, this is resulting in the error i referenced above as the Framework's extension is not being called and so it attempts to call `delete` on NSManagedObjectContext (which doesn't exist)

**Comment by jessesquires** [comment] 2016-06-03 19:06
Ugh 😢 I see now.

However, this isn't reproducible in the demo project...

@saurabytes / @MobileVet — what's different about your projects? Have you tried doing a clean build?

**Comment by MobileVet** [comment] 2016-06-03 19:38
I was pretty bummed when I couldn't get it to happen on the demo project... honestly don't see the difference.  I have a couple other frameworks and they have extensions that work... Did you see the SO link I included?  That definitely makes it sound like there is a known issue of some kind, though more around generic types. Could NSManagedObjectContext be considered 'generic' or falling under the same issue?

Here are my Build Settings:
![screen shot 2016-06-03 at 10 33 59 am](https://cloud.githubusercontent.com/assets/1977118/15790773/29e52ee2-29a1-11e6-895c-fd2bbde2a2f2.png)

Definitely done a clean build.

**Comment by jessesquires** [comment] 2016-06-03 23:46
@MobileVet — Very strange. Yes, I did look at SO.

> Could NSManagedObjectContext be considered 'generic' or falling under the same issue?

I don't think so...

--------------------

It looks like you're using carthage? Or are you manually adding the library?

I just checked this with an app I'm working on and `context.delete(objects: [obj])` is completely fine. I'm using CocoaPods.

**Comment by jessesquires** [comment] 2016-06-03 23:46
@saurabytes — Did you do a clean build? How are you integrating the lib?

**Comment by MobileVet** [comment] 2016-06-04 00:07
Thanks for all your help with this @jessesquires 
I have integrated the framework 'manually'... not using Carthage or Cocoapods

**Comment by jessesquires** [comment] 2016-06-04 00:23
Hm... 

I also just ran a clean build of the demo project, which adds the framework manually. So...

![](https://media.giphy.com/media/3ornjSL2sBcPflIDiU/giphy.gif)

**Comment by saurabytes** [comment] 2016-06-04 01:22
strangely enough now a delete call is working fine now, must have cleaned my project :). sorry for the false alarm

**Comment by jessesquires** [comment] 2016-06-04 02:01
Thanks @saurabytes !

@MobileVet - my guess is still that your build is dirty. 😊 

Going to close this out given everything above.

**Closed by jessesquires** 2016-06-04 02:01 UTC
Labels: question

**Comment by MobileVet** [comment] 2016-06-04 20:46
@jessesquires Your gif made me laugh out loud, well done.
Appreciate you looking into this.  I have done several cleans and also deleted the derived data... still no luck.  That said, I am sure there is something funny about my setup.  When I find it I will let you know.
Cheers,
