### ISSUE TITLE
Multithreading Violation while saving parent context

### ISSUE THREAD

**Issue by saurabytes** [jessesquires/JSQCoreDataKit#63] opened 2016-03-03 16:55 UTC
#### Overview
I have enabled concurrency detection for multithread violations using
`-com.apple.CoreData.ConcurrencyDebug 1` in the Run arguments
Since then every save I raising this flag. Currently it seems this is happening how the saves are being handled.
The violation happens in [save context](https://github.com/jessesquires/JSQCoreDataKit/blob/develop/Source/CoreDataExtensions.swift#L45) for parent after the `NSManagedObjectContextDidSaveNotification` is posted for the child context

<img width="511" alt="screen shot 2016-03-03 at 10 45 38 am" src="https://cloud.githubusercontent.com/assets/1922590/13499653/42abb200-e12d-11e5-9478-69757bd9d028.png">

#### Steps
1. Update `Run` in scheme for ExampleApp to have [`-com.apple.CoreData.ConcurrencyDebug 1`](http://oleb.net/media/xcode-scheme-core-data-concurrency-debug.png)
2. Add a company in the app
3. The app crashes with above stack trace
`+[NSManagedObjectContext__Multithreading_Violation_AllThatIsLeftToUsIsHonor__] ()`

**Comment by saurabytes** [comment] 2016-03-03 18:31
#### Fix
Looking more closely and verify with a test this is the resolution
The context `hasChanges` verification has to be thread safe too
```
    let block = {
        guard context.hasChanges else { return }
        do {
            try context.save()
            completion?(.Success)
        }
        catch {
            completion?(.Failure(error as NSError))
        }
    }
```

**Comment by jessesquires** [comment] 2016-03-04 01:04
Thanks @saurabytes ! :+1: 

Closing as a duplicate of #59.

If you would like to submit a PR, please do! :smile:

**Closed by jessesquires** 2016-03-04 01:04 UTC
Labels: bug, duplicate
